spec:
  restartPolicy: OnFailure
  containers:
  - name: dashy
    image: b4bz/homer
    volumeMounts:
    - name: host-path-0
      mountPath: /www/assets
      readOnly: false
  volumes:
  - name: host-path-0
    hostPath:
      path: /var/homer/config/