spec:
  restartPolicy: OnFailure
  containers:
  - name: dashy
    image: b4bz/homer
    volumeMounts:
    - name: host-path-0
      mountPath: /www/assets
      readOnly: false
    env:
      - name: PORT
        value: 80
      - name: UID
        value: 0
      - name: GUID
        value: 0
  volumes:
  - name: host-path-0
    hostPath:
      path: /var/homer/config/